let imagenes = [
    'img0.jpg',
    'img1.jpg',
    'img2.jpg',
    'img3.jpg',
    'img4.png',
    'img5.jpg',
    'img6.png',
    'img7.jpg',
    'img8.jpg',
    'img9.jpg',
    'img10.jpg',
    'img11.jpg',
    'img12.jpg',
    'img13.jpg',
    'img14.jpg',
    'img15.jpg',
    'img16.jpg',
    'img17.jpg',
    'img18.jpg',
    'img19.jpg',
    'img20.jpg',
    'img21.jpg',
    'img22.jpg',
    'img23.jpg',
    'img24.jpg',
    'img25.jpg',
    'img26.jpg',
    'img27.jpg',
    'img29.jpg',
    'img30.jpg',
    'img31.jpg',
    'img32.jpg',
    'img33.jpg',
    'img34.jpg',
    'img35.jpg',
    'img36.jpg',
    'img37.jpg',
    'img38.jpg',
    'img39.jpg',
    'img40.jpg',
    'img41.jpg',
    'img42.jpg',
    'img43.jpg',
    'img44.jpg',
    'img45.jpg',
    'img46.jpg',
    'img47.jpg',
    'img48.jpg',
    'img49.jpg',
    'img50.jpg',
    'img51.jpg',
    'img52.jpg',
    'img53.jpg',
    'img54.jpg',
    'img55.jpg',
    'img56.jpg',
    'img57.jpg',
    'img58.jpg',
    'img59.jpg',
    'img60.jpg',
    'img61.jpg',
    'img62.jpg',
    'img63.jpg',
    'img64.jpg',
    'img65.jpg',
    'img66.jpg',
    'img67.jpg',
    'img68.jpg'
]

/*Para agregar una imagen tenés que poner una ',' en el último elemento
luego, en la línea de abajo, tenés que ingresar 'imgNUM.jpg'  NUM = número de imagen que corresponde
*IMPORTANTE* => NO PONER COMA DESPUES DEL ÚLTIMO ELEMENTO INGRESADO

*--- COMANDOS ---*
git add .           *IMPORTANTE* => Si, el punto tambien
git commit -m "Imagen NUM"
git push origin main
*/